[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NEXT_PRIVATE_TARGET = "server"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[form]
  # Form settings
  [form.settings]
    # Enable form notifications
    [form.settings.notification]
      # Send form submissions to your email
      email = "ramgopalpampana120@gmail.com"
