[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable Netlify Forms
[form]
  # Form settings for contact form
  [form.settings]
    # Send form submissions to your email
    [form.settings.notification]
      email = "ramgopalpampana120@gmail.com"
